### ISSUE TITLE
Use Postgres search instead of elastic search

### ISSUE THREAD

**Issue by chriswedgwood** [django/djangosnippets.org#115]
> I think dropping elasticsearch would be a nice optimisation. (The main pro of ES is ingest rate: it’s much faster than postgres at pulling in new records: but we’re nowhere near needing that.)

Carlton Gibson

**Comment by carltongibson** [comment]
Hi @chriswedgwood — so #161 is in. 

* [Seems to work](https://djangosnippets.org/searchfulltext/?q=contrib.auth) 😀
* [Looks similar to the old one](https://djangosnippets.org/search/?q=contrib.auth)

Test successful? 

Do you think we're in a position migrate and drip ES? 

Good stuff!

**Comment by chriswedgwood** [comment]
Hi @carltongibson  yes I think we are good to go. If we have any issues we can just fix forward without ES.
I will submit a PR for this 👍
