### ISSUE TITLE
Edit comment

### ISSUE THREAD

**Issue by dimkoug** [django/djangosnippets.org#118]
How to edit  a comment i posted ?

**Comment by chriswedgwood** [comment]
Hi Dimitris

If you click on the snippet there should be a grey pencil to edit. If it is not there you may need to login first?
<img width="409" alt="Screenshot 2020-05-25 at 20 30 33" src="https://user-images.githubusercontent.com/1273523/82839305-d60b4f00-9ec6-11ea-8713-28aa5cf13891.png">

**Comment by dimkoug** [comment]
when i log in  , is there a filter to find my comments ?

**Comment by carltongibson** [comment]
I don't **think** that's possible. Would you fancy adding as a feature?

**Comment by chriswedgwood** [comment]
Sorry @dimkoug  I misread your initial post , you were talking about comments not snippets :). This is not possible right now and we would welcome this feature 👍

**Comment by chriswedgwood** [comment]
@dimkoug If you are not actively working on this I think I will start working on this feature

**Comment by dimkoug** [comment]
@chriswedgwood  i am not working on this feature.
