### ISSUE TITLE
master branch currently broken

### ISSUE THREAD

**Issue by chriswedgwood** [django/djangosnippets.org#150]
Currently the master branch is failing with isort issues as the version was not being pinned 
#148 will fix this :)

**Comment by carltongibson** [comment]
isort just released v5 which has breaking changes , not just in the commands but in the behaviour I think. 

I’m sure this is progress in the end, but it seems unstable at the moment. (5 point releases in a number of days and issues still open.)

At the moment, I’m pinning channels to <5, to give it time to settle before updating. 

Worth thinking about whether combining with black is a good idea here, whilst assessing this.

**Comment by chriswedgwood** [comment]
Okay cool I’ll raise a pr to pin isort<5

Thanks
