### ISSUE TITLE
Master brach now failing [ AttributeError: 'ParsedRequirement' object has no attribute 'req']

### ISSUE THREAD

**Issue by chriswedgwood** [django/djangosnippets.org#152]
The master build is now failing on travis during requirements installation but has not changed for some time
and it was green before.

Collecting python-akismet==0.4.1
  Downloading python-akismet-0.4.1.tar.gz (9.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/travis/virtualenv/python3.7.1/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r3yi32yh/python-akismet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r3yi32yh/python-akismet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-g7h787s2
         cwd: /tmp/pip-install-r3yi32yh/python-akismet/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-r3yi32yh/python-akismet/setup.py", line 186, in <module>
        install_requires = [str(ir.req) for ir in requirements]
      File "/tmp/pip-install-r3yi32yh/python-akismet/setup.py", line 186, in <listcomp>
        install_requires = [str(ir.req) for ir in requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'

**Comment by chriswedgwood** [comment]
This is resolved with python-akismet bump

**Comment by carltongibson** [comment]
Ah, super. Well done @chriswedgwood! 🥇
