### ISSUE TITLE
Add an api

### ISSUE THREAD

**Issue by twidi** [django/djangosnippets.org#16]
I'm working on the [Repos.io](http://repos.io) site, which allow users to search for and manage repositories, and i would add a backend for django-snippets, which is very usefull.

I could write it myself and add a pull-request but i currently have no time for it (lot of code to do for Repos.io), i just add it as a reminder or if someone has time :)

This api should handle registration (via oauth ?), and at least read access for various objects, and bookmarks (idealy it should allow to add/remove bookmarks)

All of this can be done with piston (never did it but i heard about it)

**Comment by chriswedgwood** [comment]
Is this something we want to do? Would not take that much effort and be good to showcase DRF?

**Comment by carltongibson** [comment]
HI @chriswedgwood. Yes... it's something to consider. My hope is that the app is a kind of reference: _Look, here's an actual site you can browse and copy from…_ — so a small **simple** API — perhaps just read-only, at least at first pass, would be a nice addition.
