### ISSUE TITLE
"Internal error" when I try to create account

### ISSUE THREAD

**Issue by ML-Chen** [django/djangosnippets.org#170]
I want to leave a comment on a Django Snippet on djangosnippets.org, which requires logging in. I don't currently have an account, but as I don't see a button for creating an account, I tried the log in buttons. Here's what happened with the various log in methods:

- BitBucket: "Social Network Login Failure. An error occurred while attempting to login via your social network account."
- GitHub: "There's been an internal error on the server; it probably wasn't anything you did, so don't worry too much about it. The site administrators have been emailed with the details, and they'll probably get it fixed real soon."
- Reset password with my email address which currently doesn't have an account: "There's been an internal error on the server; it probably wasn't anything you did, so don't worry too much about it. The site administrators have been emailed with the details, and they'll probably get it fixed real soon."
- Logging in with my email (which hasn't been registered) and a random keyboard mash password returns me to the login page without even a message like "log in failed"
- I haven't tried Twitter yet.

I have not received any emails from Django Snippets after these registration attempts.

If it is intentional that you can't create an account, it would probably be good to clarify this and make the error messages more informative.

The FAQ says "I've done my best to make signing up as easy as possible", linking to https://djangosnippets.org/accounts/register/, but that is a dead link.

**Comment by chriswedgwood** [comment]
Thank you for your email Michael I will look into this and get back to you

Kind regards
Chris

**Comment by chriswedgwood** [comment]
I have re-created the issue attempting to create a new account and I also get _"Error
There's been an internal error on the server; it probably wasn't anything you did, so don't worry too much about it. The site administrators have been emailed with the details, and they'll probably get it fixed real soon."_.

There is nothing showing up in  sentry so I will need to look a little longer to find the issue.

**Comment by chriswedgwood** [comment]
@ML-Chen  I haven't forgotten about this. I've been dealing with a severe technical issue at work but will look at this when things have settled. I did have a quick look and it looks like the sentry configuration may be a bit dated.

**Comment by ML-Chen** [comment]
Don't worry, take your time

**Comment by chriswedgwood** [comment]
So I have tried twitter and github and It is working for me.
Bitbucket is definitely broken and it looks like it may be issues with the way in which the app has been setup. Will need to dig deeper on this one.
I cant seem to re-create the internal server error.
@ML-Chen can you retry with twitter and/or github?
We have sorted out our sentry configuration so we will be able to capture the error and diagnose.

**Comment by ML-Chen** [comment]
Awesome, I was able to create an account with GitHub.

**Comment by chriswedgwood** [comment]
Thats great news 2/3 is not bad! I'll leave this open till we sort out bitbucket issues

**Comment by OmenApps** [comment]
I tried creating an account both via Twitter and via GitHub, and got server errors in both cases. It does seem to associate my email with an account, though. If I try to use the password reset form, I also get a server error.

**Comment by chriswedgwood** [comment]
Thanks Omen I’ll have a look 👍

**Comment by chriswedgwood** [comment]
@OmenApps Ive re-created the issue on the live site and will need to figure out what has changed as we haven't deployed for a while.
Will  let you know when its fixed 👍

**Comment by chriswedgwood** [comment]
![image](https://user-images.githubusercontent.com/1273523/109080949-56cad600-76f9-11eb-9d05-bfe7ce52ed27.png)

The issue seems to lie with sendgrid. I'm going to wait till these issues are resolved before doing further investigations

**Comment by chriswedgwood** [comment]
![image](https://user-images.githubusercontent.com/1273523/109124116-789c7b00-7742-11eb-944a-aa80b13a9004.png)

The error is coming out of Python smtp lib when trying to send an email. Going to try recreate this locally with python3.7

**Comment by chriswedgwood** [comment]
@OmenApps  This has been resolved. Please try log in and see if you can get in. You twitter and github accounts were successfully created.

Im not sure if Sendgrid has changed but we were not following this documentation:
https://sendgrid.com/docs/for-developers/sending-email/django/
