### ISSUE TITLE
Sentry is not picking up issues with allauth

### ISSUE THREAD

**Issue by chriswedgwood** [django/djangosnippets.org#171]
I have been trying to look into #170 which suggests that there is an issue with allauth but no issues are popping up in sentry for it.

**Comment by carltongibson** [comment]
Hmmm. _Are we actually logging errors?_ is my immediate thought. 🤔

**Comment by chriswedgwood** [comment]
I’ll review and get and get back to you 👍

**Comment by chriswedgwood** [comment]
@carltongibson  I haven't forgotten about this. I've been dealing with a severe technical issue at work but will look at this when things have settled. I did have a quick look and it looks like the sentry configuration may be a bit dated.

**Comment by carltongibson** [comment]
Hey @chriswedgwood — No problem! 

I've not forgotten about #164 either. 😀
