### ISSUE TITLE
Rest User

### ISSUE THREAD

**Issue by guettli** [django/djangosnippets.org#206]
Hi,

could you please reset my user account `guettli`

I created a snippet several years ago: https://djangosnippets.org/snippets/646/

I would like to update the text to:

-------

You can use the [pytest-django setting](https://pytest-django.readthedocs.io/en/latest/configuring_django.html#pytest-ini-settings) FAIL_INVALID_TEMPLATE_VARS 

The invaild vars get checked if pytest executes the code.

```
[pytest]
DJANGO_SETTINGS_MODULE = mysite.settings
FAIL_INVALID_TEMPLATE_VARS = True
```

-------

My old email-address hv@tbz-pariv.de does not exist any more.

**Comment by chriswedgwood** [comment]
Hi Thomas 

Thanks for getting in touch. Can I change your email address to guettliml@thomas-guettler.de?
