### ISSUE TITLE
NAVBAR and Background

### ISSUE THREAD

**Issue by himanshu007-creator** [django/djangosnippets.org#208]
HI
I have some suggestions regarding navbar and background.
1) Currently, the navbar is quite small, It should be changed.It should be made a bit more long (height++). We can use icons to make it look good. It should  have a color code that depicts message visually
    - RED COLOR NAVBAR means you are currently not logged in 
    - GREEN COLOR NAVBAR means you are logged in
    - USERNAME logo can also be used for this purpose.If logo is without tick, it means you are not logged in and if tick, means l 
      logged in
 2)We can improve background to make it user friendly. WE can create a theme toggling button , or simply create a javascript that detects user's timezone and according to it, changes theme to light or dark,

Implementing these changes will make website look better adding to user experience.
I would like to work on there issues ( if allowed )

**Comment by chriswedgwood** [comment]
Hi Himanshu

Yes agreed it is looking like it is need of a styling refresh. You are absolutely allowed to work on this :) 

Let me know if you need any help

**Comment by himanshu007-creator** [comment]
> Hi Himanshu
> 
> Yes agreed it is looking like it is need of a styling refresh. You are absolutely allowed to work on this :)
> 
> Let me know if you need any help

Thank you sir, I will surely let you know.
