### ISSUE TITLE
Redis Error - max number of clients reached

### ISSUE THREAD

**Issue by chriswedgwood** [django/djangosnippets.org#224]
This error is popping up in sentry.

I'm not that familiar with redis, will do some research and  investigate :)

**Comment by carltongibson** [comment]
Hey @chriswedgwood — that's a good one. Can you link the issue here in Sentry? (Let me know if not, and I'll poke around in the Sentry UI to see if we can get that going.)

**Comment by chriswedgwood** [comment]
Here you go...

https://sentry.io/share/issue/07d9acfe9e0e4cc7bf71051b88d2c894/

**Comment by chriswedgwood** [comment]
@carltongibson  Looking in the redis config:
![image](https://user-images.githubusercontent.com/1273523/109959002-c97e1780-7cde-11eb-9ea3-8dcbe97d8ce4.png)

We have max connections of 50. Our plan doesn't enable us to see connection history graphs so hard to know whats happening. The only thing I can think to do is restart redis. I can query redis sporadically and see if connections are kept over time.

Or maybe we can upgrade redis?

**Comment by carltongibson** [comment]
> The only thing I can think to do is restart redis. 

Route 1. 😄 👍 

> I can query redis sporadically and see if connections are kept over time.

I can't see why a little app like this need 50 connections. So this might be worth a play. (Just casually)

**Comment by chriswedgwood** [comment]
Restarted redis. CLIENT LIST is currently showing 5 connections
Closing issue.

**Comment by carltongibson** [comment]
Thanks @chriswedgwood — it may be there's some slow connection leak somewhere... but... 😀

**Comment by chriswedgwood** [comment]
I'll keep an eye out for it 👍
