### ISSUE TITLE
Development setup instructions for windows users missing

### ISSUE THREAD

**Issue by datencoach** [django/djangosnippets.org#267]
I think it would be a good idea to include setup instructions for windows users into the development setup.

PostgreSQL setup on Windows is not self-explaining and does not work very well in my opinion. I think using WSL2 to create a linux subsystem and handle PostgreSQL there ist the best option.

Using Sqlite is not possible due to an error "no such function: to_tsvector" due to 
OperationalError at /snippets/5/ - no such function: to_tsvector @ http://127.0.0.1:8000/snippets/5/

**Comment by LucasSD** [comment]
I've recently set up the development environment in Windows using PostgreSQL, but without using WSL2. I'm happy to improve the setup instructions for Windows users if @chriswedgwood wants to assign this issue to me?
