### ISSUE TITLE
Travis-Ci.org is no longer need to move to .com or github actions

### ISSUE THREAD

**Issue by chriswedgwood** [django/djangosnippets.org#284]
![image](https://user-images.githubusercontent.com/1273523/122452832-9451b880-cfa1-11eb-8a9c-698793683367.png)

I will need one of the ops team to set up travis-ci.com for us I think.

The other option is to move to github actions?

Im Happy with either

**Comment by carltongibson** [comment]
Hey @chriswedgwood. I think GHA is the way forward. 

Adding Travis to the Django Org is a bit broad brush given that it's a dying service.
