### ISSUE TITLE
Add 1.10 to the snippet version choices

### ISSUE THREAD

**Issue by jribbens** [django/djangosnippets.org#41]
The latest version you can indicate is 1.7.

**Comment by timgraham** [comment]
I added 1.8 and 1.9 in eb10ca329c359a8c25323d2b52b6bb4386c32870 but 1.10 requires a schema migration. I'd rather use Django migrations than south, so I'm working on upgrading Django so we can do that.

**Comment by timgraham** [comment]
Fixed in 9dc2f2bed0e27d48d60089b0dda7fa0ca707a13a.
