### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by chriswedgwood** [django/djangosnippets.org#413]
I'll look into this tonight 💯 

Need to set up alerts for this to my email to stay on top of this

**Comment by carltongibson** [comment]
Thanks @chriswedgwood 🙏

**Comment by chriswedgwood** [comment]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/1273523/184421354-44fff580-0624-4249-bc4e-e2e13fa3eaae.png">

**Comment by chriswedgwood** [comment]
Any opinions on what redis solution to use:

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/1273523/184421563-4aea4c39-3256-43f6-b0fe-1abbe0d8a9b0.png">

**Comment by carltongibson** [comment]
Grrr. Grumble. Right. 🤔

(Some investigating follows...)

**Comment by carltongibson** [comment]
Hey @chriswedgwood — Redis Enterprise Cloud has a free plan that should be more than sufficient. 

Do you want to click that button and see what details are needed and we can coordinate via the ops email to resolve?
Thanks! 🏅

**Comment by chriswedgwood** [comment]
Great thanks @carltongibson  I'll do that and send an email to ops 👍

**Comment by chriswedgwood** [comment]
This has been resolved with #414  and adding  Redis Enterprise Cloud as per above. We are using the free version. I will monitor  our usage going forward

**Comment by carltongibson** [comment]
Great work. Thanks @chriswedgwood
