### ISSUE TITLE
Cannot upload new snippets

### ISSUE THREAD

**Issue by jribbens** [django/djangosnippets.org#42]
You cannot upload new snippets - it just says "Please correct the errors below:" but then lists no errors below.

I haven't done anything fancy with my input that would be an obvious cause of failure. The only thing I can think of is that I have left the "Version" as "Not specified", because 1.9 isn't an available option, and I left "Tags" blank.

**Comment by timgraham** [comment]
Tag is required but the error message didn't display. Fixed in 9d94bae73f4ac44cd90d9ac1fa5964e9f5fa23b2.
