### ISSUE TITLE
reCAPTCHA v1 is shut down

### ISSUE THREAD

**Issue by michaelmior** [django/djangosnippets.org#63]
See https://developers.google.com/recaptcha/docs/faq

**Comment by abulka** [comment]
Is this why I cannot post a comment to a snippet?  The captcha field just screams red saying the field is required but there is nothing I can see that I can type in.

**Comment by michaelmior** [comment]
Yup, that would be why!

**Comment by timgraham** [comment]
Updated to django-recapatch 2.0.2 in a0e056afe35ce589f68b1bd892e5a9d0ef5f2870 and confirmed that comments work.
