### ISSUE TITLE
Would you like help?

### ISSUE THREAD

**Issue by chriswedgwood** [django/djangosnippets.org#93]
Hi  I just listened to the Django Chat podcast and would like to get involved in some kore open source work.
I would be happy to give this project some time. Is there anything that you would like done or a new piece of functionality added?

**Comment by carltongibson** [comment]
Hi @chriswedgwood. Yes. Super. Welcome. 🙂

If you look at the PRs, there’s various dependcy updates. Most of those are no problem but, for example, can we update to the latest Django? That needs a manual verification. And so on. 

Then beyond maintenance tasks, can we give the app an update? There’s no reason why it couldn’t continue to be a good resource going forward, but it does need some love. 

If you have a hour or two a week and the willingness then yes djangosnippets could really do with that time. If you were to take it on, I’d be happy to advise on particular issues.

**Comment by chriswedgwood** [comment]
Hi @carltongibson thanks for getting back to me. Yes I would be very happy to take it on and can give it some time. I've forked and will familiarise myself with the project along with manually testing the upgrade path to Django 3.0.4. In terms of the upgrade process is the correct way to create pull requests for each latest patch release -> deploy -> repeat?

**Comment by carltongibson** [comment]
@chriswedgwood Super. Thanks. I think for updates (the dependabot PRs) a manual verification: "Yes, I tested this and it works" would be enough for now. (It's that someone took the time to check... 🙂) 

Comment on individual issues if you have questions. 
Open an issue to discuss when you're at the stage of "Hey, this would be an improvement". 

Welcome aboard! ⛵️

(I'm going to close this as resolved.)
